name: Guokr Signins
author: guokr
description: 'signin automatically'

inputs:
  GP_TOKEN:
    description: 'Github personal access token'
    required: false
    default: ''

  TIEBA_BDUSS:
    description: 'TIEBA_BDUSS'
    required: false
    default: ''

  FULIBA_COOKIE:
    description: 'FULIBA_COOKIE'
    required: false
    default: ''
  FULIBA_USERNAME:
    description: 'FULIBA_USERNAME'
    required: false
    default: ''

  GLADOS_COOKIE:
    description: 'GLADOS_COOKIE'
    required: false
    default: ''

  PUSHPLUS_TOKEN:
    description: 'PushPlus token'
    required: false
    default: ''
  PUSHPLUS_TOPIC:
    description: 'PushPlus topic'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - id: version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: GuokrSun/auto-signin
        excludes: prerelease, draft
    - name: Download
      shell: bash
      run: |
        wget https://github.com/GuokrSun/auto-signin/archive/refs/tags/${{ steps.version.outputs.release }}.zip -O release.zip
        rm -rf release
        unzip release.zip -d release
        rm release.zip
    - name: Run
      shell: bash
      run: |
        cd release
        cd $(ls -dt */|head -1 )
        pip install -r requirements.txt
        python app.py -a
      env:
        GP_TOKEN: ${{ inputs.GP_TOKEN }}
        GITHUB_REPOS: ${{ github.repository }}
        TIEBA_BDUSS: ${{ inputs.TIEBA_BDUSS }}
        GLADOS_COOKIE: ${{ inputs.GLADOS_COOKIE }}
        FULIBA_COOKIE: ${{ inputs.FULIBA_COOKIE }}
        FULIBA_USERNAME: ${{ inputs.FULIBA_USERNAME }}
        PUSHPLUS_TOKEN: ${{ inputs.PUSHPLUS_TOKEN }}
        PUSHPLUS_TOPIC: ${{ inputs.PUSHPLUS_TOPIC }}

branding:
    icon: 'check-circle'
    color: 'orange'