name: Guokr Signins
author: guokr
description: 'signin automatically'

inputs:
  TIEBA_TOKEN:
    description: 'TIEBA_TOKEN'
    required: false
    default: ''

  FULIBA_COOKIE:
    description: 'FULIBA_COOKIE'
    required: false
    default: ''
  FULIBA_USERNAME:
    description: 'FULIBA_USERNAME'
    required: false
    default: ''

  GLADOS_COOKIE:
    description: 'GLADOS_COOKIE'
    required: false
    default: ''

  ZDM_COOKIE:
    description: 'ZDM_COOKIE'
    required: false
    default: ''

  PUSHPLUS_TOKEN:
    description: 'PushPlus token'
    required: false
    default: ''
  PUSHPLUS_TOPIC:
    description: 'PushPlus topic'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - id: version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: GuokrSun/auto-signin
        excludes: prerelease, draft
        token: ${{ inputs.GP_TOKEN }}
    - name: Download
      shell: bash
      run: |
        wget https://github.com/GuokrSun/auto-signin/archive/refs/tags/${{ steps.version.outputs.release }}.zip -O release.zip
        rm -rf release
        unzip release.zip -d release
        rm release.zip
    - name: Run
      shell: bash
      run: |
        cd release
        cd $(ls -dt */|head -1 )
        pip install -r requirements.txt
        python app.py -a
      env:
        TIEBA_TOKEN: ${{ inputs.TIEBA_TOKEN }}
        FULIBA_COOKIE: ${{ inputs.FULIBA_COOKIE }}
        FULIBA_USERNAME: ${{ github.FULIBA_USERNAME }}
        GLADOS_COOKIE: ${{ inputs.GLADOS_COOKIE }}
        ZDM_COOKIE: ${{ inputs.ZDM_COOKIE }}
        PUSHPLUS_TOKEN: ${{ inputs.PUSHPLUS_TOKEN }}
        PUSHPLUS_TOPIC: ${{ inputs.PUSHPLUS_TOPIC }}

branding:
    icon: 'check-circle'
    color: 'orange'