name: 开始每日签到

on:
  workflow_dispatch:
  schedule:
    # UTC 1点30分(北京时间 9点30分)
    - cron: 30 1 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run
        run: |
          python app.py
        env: 
          TIEBA_TOKEN: "${{ secrets.TIEBA_TOKEN }}"
          FULIBA_COOKIE: ${{ secrets.FULIBA_COOKIE }}
          FULIBA_USERNAME: ${{ secrets.FULIBA_USERNAME }}
          GLADOS_COOKIE: ${{ secrets.GLADOS_COOKIE }}
          ZDM_COOKIE: ${{ secrets.ZDM_COOKIE }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          PUSHPLUS_TOPIC: ${{ secrets.PUSHPLUS_TOPIC }}
      - uses: gautamkrishnar/keepalive-workflow@master  
