name: signin

on:
  workflow_dispatch:
  schedule:
    # UTC 1点30分(北京时间 9点30分)
    - cron: 30 1 * * *

jobs:
  signin:
    name: signin
    runs-on: ubuntu-latest
    steps:
      - uses: GuokrSun/auto-signin@main
        with:
          TIEBA_TOKEN: ${{ secrets.TIEBA_TOKEN }}
          FULIBA_COOKIE: ${{ secrets.FULIBA_COOKIE }}
          FULIBA_USERNAME: ${{ secrets.FULIBA_USERNAME }}
          GLADOS_COOKIE: ${{ secrets.GLADOS_COOKIE }}
          ZDM_COOKIE: ${{ secrets.ZDM_COOKIE }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          PUSHPLUS_TOPIC: ${{ secrets.PUSHPLUS_TOPIC }}
